import turtle




turtle.speed(0)
my_pen = turtle.Pen()
turtle.bgcolor("black")


for x in range(2):

  my_pen.pencolor("red")
  my_pen.width(x/100 + 1)
  my_pen.circle(100)
  my_pen.right(90)
  my_pen.circle(100)
  my_pen.right(90)
  my_pen.circle(100)
  my_pen.right(90)
  my_pen.circle(100)
   
  my_pen.pencolor("orange")
  my_pen.width(x/100 + 1)
  my_pen.circle(95)
  my_pen.right(90)
  my_pen.circle(95)
  my_pen.right(90)
  my_pen.circle(95)
  my_pen.right(90)
  my_pen.circle(95)

  my_pen.pencolor("yellow")
  my_pen.width(x/100 + 1)
  my_pen.circle(90)
  my_pen.right(90)
  my_pen.circle(90)
  my_pen.right(90)
  my_pen.circle(90)
  my_pen.right(90)
  my_pen.circle(90)

  my_pen.pencolor("green")
  my_pen.width(x/100 + 1)
  my_pen.circle(85)
  my_pen.right(90)
  my_pen.circle(85)
  my_pen.right(90)
  my_pen.circle(85)
  my_pen.right(90)
  my_pen.circle(85)

  my_pen.pencolor("blue")
  my_pen.width(x/100 + 1)
  my_pen.circle(80)
  my_pen.right(90)
  my_pen.circle(80)
  my_pen.right(90)
  my_pen.circle(80)
  my_pen.right(90)
  my_pen.circle(80)

  my_pen.pencolor("purple")
  my_pen.width(x/100 + 1)
  my_pen.circle(75)
  my_pen.right(90)
  my_pen.circle(75)
  my_pen.right(90)
  my_pen.circle(75)
  my_pen.right(90)
  my_pen.circle(75)

  my_pen.pencolor("red")
  my_pen.width(x/100 + 1)
  my_pen.circle(70)
  my_pen.right(90)
  my_pen.circle(70)
  my_pen.right(90)
  my_pen.circle(70)
  my_pen.right(90)
  my_pen.circle(70)
   
  my_pen.pencolor("orange")
  my_pen.width(x/100 + 1)
  my_pen.circle(65)
  my_pen.right(90)
  my_pen.circle(65)
  my_pen.right(90)
  my_pen.circle(65)
  my_pen.right(90)
  my_pen.circle(65)

  my_pen.pencolor("yellow")
  my_pen.width(x/100 + 1)
  my_pen.circle(60)
  my_pen.right(90)
  my_pen.circle(60)
  my_pen.right(90)
  my_pen.circle(60)
  my_pen.right(90)
  my_pen.circle(60)

  my_pen.pencolor("green")
  my_pen.width(x/100 + 1)
  my_pen.circle(55)
  my_pen.right(90)
  my_pen.circle(55)
  my_pen.right(90)
  my_pen.circle(55)
  my_pen.right(90)
  my_pen.circle(55)


  my_pen.pencolor("blue")
  my_pen.width(x/100 + 1)
  my_pen.circle(50)
  my_pen.right(90)
  my_pen.circle(50)
  my_pen.right(90)
  my_pen.circle(50)
  my_pen.right(90)
  my_pen.circle(50)

  my_pen.pencolor("purple")
  my_pen.width(x/100 + 1)
  my_pen.circle(45)
  my_pen.right(90)
  my_pen.circle(45)
  my_pen.right(90)
  my_pen.circle(45)
  my_pen.right(90)
  my_pen.circle(45)

  
  my_pen.pencolor("red")
  my_pen.width(x/100 + 1)
  my_pen.circle(40)
  my_pen.right(90)
  my_pen.circle(40)
  my_pen.right(90)
  my_pen.circle(40)
  my_pen.right(90)
  my_pen.circle(40)
   
  my_pen.pencolor("orange")
  my_pen.width(x/100 + 1)
  my_pen.circle(35)
  my_pen.right(90)
  my_pen.circle(35)
  my_pen.right(90)
  my_pen.circle(35)
  my_pen.right(90)
  my_pen.circle(35)

  my_pen.pencolor("yellow")
  my_pen.width(x/100 + 1)
  my_pen.circle(30)
  my_pen.right(90)
  my_pen.circle(30)
  my_pen.right(90)
  my_pen.circle(30)
  my_pen.right(90)
  my_pen.circle(30)

  my_pen.pencolor("green")
  my_pen.width(x/100 + 1)
  my_pen.circle(25)
  my_pen.right(90)
  my_pen.circle(25)
  my_pen.right(90)
  my_pen.circle(25)
  my_pen.right(90)
  my_pen.circle(25)


  my_pen.pencolor("blue")
  my_pen.width(x/100 + 1)
  my_pen.circle(20)
  my_pen.right(90)
  my_pen.circle(20)
  my_pen.right(90)
  my_pen.circle(20)
  my_pen.right(90)
  my_pen.circle(20)

  my_pen.pencolor("purple")
  my_pen.width(x/100 + 1)
  my_pen.circle(15)
  my_pen.right(90)
  my_pen.circle(15)
  my_pen.right(90)
  my_pen.circle(15)
  my_pen.right(90)
  my_pen.circle(15)

  my_pen.pencolor("red")
  my_pen.width(x/100 + 1)
  my_pen.circle(10)
  my_pen.right(90)
  my_pen.circle(10)
  my_pen.right(90)
  my_pen.circle(10)
  my_pen.right(90)
  my_pen.circle(10)
   
  my_pen.pencolor("orange")
  my_pen.width(x/100 + 1)
  my_pen.circle(5)
  my_pen.right(90)
  my_pen.circle(5)
  my_pen.right(90)
  my_pen.circle(5)
  my_pen.right(90)
  my_pen.circle(5)


   




turtle.done()

